// Import the original config from the @wordpress/scripts package.
const defaultConfig = require('@wordpress/scripts/config/webpack.config');

// Import the helper to find and generate the entry points in the src directory
const { getWebpackEntryPoints } = require('@wordpress/scripts/utils/config');

const BrowserSyncPlugin = require('browser-sync-webpack-plugin');

// Plugins.
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts');
const CopyPlugin = require('copy-webpack-plugin');

// Utilities.
const path = require('path');

// Add any a new entry point by extending the webpack config.
module.exports = {
	...defaultConfig,
	...{
		entry: {
			...getWebpackEntryPoints(),
			'scripts/app': path.resolve(process.cwd(), 'src/scripts', 'app.js'),
			'scripts/gsap': path.resolve(process.cwd(), 'src/scripts', 'gsap.js'),
			'scripts/smoothscroll': path.resolve(process.cwd(), 'src/scripts', 'smoothscroll.js'),
			'scripts/editorial-block-plugin': path.resolve(process.cwd(), 'src/scripts', 'editorial-block-plugin.js'),
			'scripts/image-credits-block-plugin': path.resolve(process.cwd(), 'src/scripts', 'image-credits-block-plugin.js'),
			'scripts/cover-block-plugin': path.resolve(process.cwd(), 'src/scripts', 'cover-block-plugin.js'),
			'scripts/wh-block-plugin': path.resolve(process.cwd(), 'src/scripts', 'wh-block-plugin.js'),
			'scripts/location-block-plugin': path.resolve(process.cwd(), 'src/scripts', 'location-block-plugin.js'),
			'scripts/hair-makeup-credits-block-plugin': path.resolve(process.cwd(), 'src/scripts', 'hair-makeup-credits-block-plugin.js'),
			'styles/app': path.resolve(process.cwd(), 'src/styles', 'app.css'),
			'styles/editor': path.resolve(process.cwd(), 'src/styles', 'editor.css')
		},
		plugins: [
			// Very important! Include WP's plugin config or the
			// world will cease to exist as we know it.
			...defaultConfig.plugins,

			// Removes the empty `.js` files generated by webpack but
			// sets it after WP has generated its `*.asset.php` file.
			new RemoveEmptyScriptsPlugin({
				stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS
			}),

			// Copies any assets that don't need to be processed to
			// the output folder.
			new CopyPlugin({
				patterns: [
					{
						from: './src/assets',
						to: './assets'
					},
					{
						from: './src/block-variations',
						to: './block-variations'
					},
				]
			}),
			new BrowserSyncPlugin(
				// BrowserSync options
				{
					// browse to http://localhost:3000/ during development
					host: 'localhost',

					port: 3000,
					// proxy the Webpack Dev Server endpoint
					// (which should be serving on http://localhost:3100/)
					// through BrowserSync
					proxy: 'http://laartsonline.local',
					files: ['**/*.css', '**/*.php', '**/*.js'],
				},
			),
		]
	},
	cache: false,
};
