import { expect, test } from '@playwright/test';

/**
 * Smoke tests.
 *
 * These assert that the theme boots and renders — no PHP fatals, no missing
 * assets, no blank page. They are intentionally shallow: their job is to catch
 * the class of breakage where the site is down entirely, which is exactly what
 * a refactor of the bootstrap or asset pipeline can cause.
 */

test.describe('theme smoke', () => {
	test('home page renders without a PHP error', async ({ page }) => {
		const response = await page.goto('/');

		expect(response?.status()).toBe(200);

		const body = await page.textContent('body');
		expect(body).not.toContain('Fatal error');
		expect(body).not.toContain('Parse error');
		expect(body).not.toContain('Warning: ');
		expect(body).not.toContain('Deprecated: ');

		// A blank page still returns 200 — assert something actually rendered.
		await expect(page.locator('body')).not.toBeEmpty();
	});

	test('theme stylesheet and app script load', async ({ page }) => {
		const failed: string[] = [];

		page.on('response', (response) => {
			const url = response.url();
			if (url.includes('/themes/laao/') && response.status() >= 400) {
				failed.push(`${response.status()} ${url}`);
			}
		});

		await page.goto('/');

		expect(
			failed,
			`theme assets returned errors:\n${failed.join('\n')}`
		).toHaveLength(0);
	});

	test('no uncaught console errors on the home page', async ({ page }) => {
		const errors: string[] = [];

		page.on('pageerror', (error) => errors.push(error.message));
		page.on('console', (message) => {
			if (message.type() === 'error') {
				errors.push(message.text());
			}
		});

		await page.goto('/');
		await page.waitForLoadState('networkidle');

		expect(errors, `console errors:\n${errors.join('\n')}`).toHaveLength(0);
	});

	test('loads no third-party assets', async ({ page }) => {
		// The theme bundles GSAP and Lenis from npm; nothing should be fetched
		// from a public CDN. A CDN dependency is an uncontrolled request on
		// every page view, a privacy exposure, and — when the URL carries a
		// floating tag like @next — a library that can change without a deploy.
		const external: string[] = [];
		const siteHost = new URL(
			process.env.WP_BASE_URL ?? 'http://localhost:9930'
		).hostname;

		page.on('request', (request) => {
			const url = new URL(request.url());

			// blob:, data: and about: are generated by the page itself and
			// never reach the network — they also parse with an empty hostname,
			// so they must be filtered before the host comparison.
			if (url.protocol !== 'http:' && url.protocol !== 'https:') {
				return;
			}

			if (url.hostname !== siteHost) {
				external.push(request.url());
			}
		});

		await page.goto('/');
		await page.waitForLoadState('networkidle');

		expect(
			external,
			`third-party requests:\n${external.join('\n')}`
		).toHaveLength(0);
	});

	test('preloads the woff2 brand fonts, not the ttf fallbacks', async ({
		page,
	}) => {
		await page.goto('/');

		const preloads = await page
			.locator('link[rel="preload"][as="font"]')
			.evaluateAll((links) =>
				links.map((link) => ({
					href: link.getAttribute('href') ?? '',
					type: link.getAttribute('type') ?? '',
				}))
			);

		expect(preloads.length).toBeGreaterThan(0);

		for (const preload of preloads) {
			// A preload that does not match the URL the @font-face resolves to
			// is worse than none: it downloads a file the browser never uses
			// while competing with the one it does.
			expect(preload.href).toContain('.woff2');
			expect(preload.href).not.toContain('.ttf');
			expect(preload.type).toBe('font/woff2');
		}
	});
});
