name: Build Release

# Controls when the action will run.
on:
  push:
    branches:
      - "master"

  workflow_dispatch:

env:
  RELEASE_FILE_NAME: "laao"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Building Release
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      # - name: Running Linter:JS
      #   run: pnpm lint:js

      # - name: Running Linter:CSS
      #   run: pnpm lint:css

      - name: Building Theme
        run: pnpm build

      - name: Package Build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.RELEASE_FILE_NAME }}
          path: |
            **/*
            !.git
            !.github
            !.vscode
            !node_modules
            !src
            !.editorconfig
            !.gitignore
            !.prettierrc
            !.stylelintignore
            !.stylelintrc.json
            !laao-webpack.config.js
            !package.json
            !pnpm-lock.yaml
            !postcss.config.js
            !README.md
            !tailwind.config.js
          retention-days: 1

  release:
    name: Build Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.RELEASE_FILE_NAME }}

      - name: Getting & Setting Version
        run: |
          APP_VERSION_NUMBER=$(grep -Po '(?<=Version:)[^;]+' ./style.css | sed -e 's/^[ \t]*//')
          echo "VERSION_NUMBER=$APP_VERSION_NUMBER" >> $GITHUB_ENV

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: "laao.zip"

      - name: Create New Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION_NUMBER }}"
          release_name: "LAAO v${{ env.VERSION_NUMBER }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./laao.zip
          asset_name: laao.zip
          asset_content_type: application/zip
